
runtime: python
env: flex
threadsafe: true
entrypoint: gunicorn -c gunicorn.conf.py -b :$PORT main:app

runtime_config:
  python_version: 3

# This beta setting is necessary for the db hostname parameter to be able to handle a URI in the
# form “/cloudsql/...” where ... is the instance given here:
beta_settings:
    cloud_sql_instances: provost-access-148820:us-east1:cuny-courses

# 2017-09-17 SendGrid configuration.
env_variables:
    SENDGRID_API_KEY: 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
