
runtime: python
env: flex
threadsafe: true
entrypoint: gunicorn -c gunicorn.conf.py -b :$PORT main:app

runtime_config:
  python_version: 3

# Attempts to control 502 Gateway Errors by disabling or reducing the frequency of health checks
# have not been successful. The default is to enable them once a second.

# health_check:
#   enable_health_check: False
#   check_interval_sec: 5
#   timeout_sec: 4
#   unhealthy_threshold: 2
#   healthy_threshold: 2
