
runtime: python
env: flex
threadsafe: true
entrypoint: gunicorn -c gunicorn.conf.py -b :$PORT main:app

runtime_config:
  python_version: 3

# health_check:
#   enable_health_check: True
#   check_interval_sec: 5
#   timeout_sec: 4
#   unhealthy_threshold: 2
#   healthy_threshold: 2
